import './editor.scss'

import './blocks/advantages'
import './blocks/contacts'
import './blocks/contacts-info'
import './blocks/definition'
import './blocks/image-left'
import './blocks/image-list'
import './blocks/our-works'
import './blocks/page-heading'
import './blocks/pages-cards'
import './blocks/slider'
